export default {
  extends: ["@commitlint/config-conventional"],
  plugins: ["commitlint-plugin-function-rules"],
  rules: {
    "body-leading-blank": [1, "always"],
    "body-max-line-length": [0],
    "footer-leading-blank": [1, "always"],
    "header-max-length": [0, "always", 72],
    "scope-case": [2, "always", "lower-case"],
    "subject-case": [0, "always", ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"],
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
  },
};
