id: bde132ed-0f25-49b7-a5d5-35790f000999
name: Break Glass Account has Signin-Activity
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: Scheduled
apiVersion: 2021-10-01-preview
properties:
  displayName: Break Glass Account has Signin-Activity
  description: >-
    he emergency access or "Break Glass Account" has recorded sign-in activity. In the context of cybersecurity, a Break Glass Account is a special-purpose account with elevated privileges that is typically used in emergency situations or when regular access mechanisms fail.
    Ref :
    https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/security-emergency-access

    This rule needs a watchlist named "BreakGlassAccounts" to be created in the Sentinel portal, where the watchlist item(searchKey) must be in all lowercase because it must match the UserPrincipalName from SigninLogs
  severity: High
  enabled: true
  query: >
    SigninLogs
    | lookup kind=inner _GetWatchlist('BreakGlassAccounts') on $left.UserPrincipalName == $right.SearchKey
  queryFrequency: PT10M
  queryPeriod: PT10M
  triggerOperator: GreaterThan
  triggerThreshold: 0
  suppressionDuration: PT5H
  suppressionEnabled: false
  tactics:
    - Persistence
  techniques:
    - T1078
  alertRuleTemplateName: null
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: false
      reopenClosedIncident: false
      lookbackDuration: PT5H
      matchingMethod: AllEntities
      groupByEntities: []
      groupByAlertDetails: []
      groupByCustomDetails: []
  eventGroupingSettings:
    aggregationKind: SingleAlert
  alertDetailsOverride:
    alertDisplayNameFormat: null
    alertDescriptionFormat: null
    alertTacticsColumnName: null
    alertSeverityColumnName: null
  customDetails: null
  sentinelEntitiesMappings: null
  templateVersion: null
