---
name: Create release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the release tag (e.g., v1.0.0)'
        required: true
permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes